### ISSUE TITLE
fullelite: add an jadebox option to reward exhibits for all elites

### ISSUE THREAD

**Issue by scarf005** [Neoshrimp/TheGoodLBoLMods#1]
Currently, enemies converted to elite via fullelite mod does not give the same reward as actual elite monsters. For regular enemies (turned into elites by fullelite mod) fight, It'd be great be able to to get same reward as elite enemies (card bonus + exhibit bonus).

**Comment by Neoshrimp** [comment]
Sorry for late reply.
Regular fight nodes not giving extra rewards is intentional. Even Block Toys alone is enough to give substantial power boost after several fights. Right now the biggest balancing issue, from my point of view, is that with 'default' difficulty bonuses (+50P and 4 card draft) the first 4-5 fights are very swingy in terms of difficulty. Taking -30hp or wasting a bomb is a surefire way to lose with a couple floors of bad rng. Afraid, giving an extra exhibit would only make mid/endgame busted. 
That being said, as difficulty is already customizable, don't see why exhibit reward after every fight couldn't be an additional jadebox bonus.

**Comment by Neoshrimp** [comment]
<https://thunderstore.io/c/touhou-lost-branch-of-legend/p/TeamNeo/FullElite/> added in 1.1.40
